// Defined constants

// Auth
export const REDIRECT_LOGGED_IN = 'REDIRECT_LOGGED_IN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const RETURN_LOGIN = 'RETURN_LOGIN';

// Statuses
export const STATUSES_RECIEVED = 'STATUSES_RECIEVED';
export const PROJECT_STATUSES_RECIEVED = 'PROJECT_STATUSES_RECIEVED';

// Towns
export const TOWNS_RECIEVED = 'TOWNS_RECIEVED';

// Tasks
export const TASKS_RECIEVED = 'TASKS_RECIEVED';
export const TASKS_ADD_RECIEVED = 'TASKS_ADD_RECIEVED';
export const TASKS_DETAIL_IMAGES_RECIEVED = 'TASKS_DETAIL_IMAGES_RECIEVED';
export const TASKS_DETAIL_IMAGES_REMOVED = 'TASKS_DETAIL_IMAGES_REMOVED';
export const TASKS_FILTER = 'TASKS_FILTER';
export const TASK_VISITED = 'TASK_VISITED';

export const TASK_RECIEVED = 'TASK_RECIEVED';

// Companies
export const COMPANIES_RECIEVED = 'COMPANIES_RECIEVED';

// Projects
export const PROJECTS_RECIEVED = 'PROJECTS_RECIEVED';


// User
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_STATUSES_RECIEVED = 'USER_STATUSES_RECIEVED';
export const USER_TASKMASTERS_RECIEVED = 'USER_TASKMASTERS_RECIEVED';
export const USER_AGENTS_RECIEVED = 'USER_AGENTS_RECIEVED';
